language: java
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn -version
  - mvn clean
  - pdd --source=$(pwd) --file=/dev/null
  - est --dir=est --file=/dev/null
  - mvn clean install -Pqulice -Pjacoco --errors --batch-mode
before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - gem install pdd -v 0.20.5
  - gem install est -v 0.3.4
  - gem install xcop -v 0.6
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
  #- openjdk6 - jcabi-http doesn't work with JDK 6
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
